---
grails:
    profile: web
    codegen:
        defaultPackage: library
    gorm:
        reactor:
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

spring:
    servlet:
        multipart:
            enabled: true
            max-file-size: 5MB
            max-request-size: 5MB
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
my:
    google:
        books:
            apiKey: "AIzaSyC5hQIIUNARqr6D8zDhRFOhv47ztYv0wKo"


environments:
    development:
        management:
            endpoints:
                enabled-by-default: true
                web:
                    base-path: '/actuator'
                    exposure:
                        include: '*'
    production:
        management:
            endpoints:
                enabled-by-default: false

---
grails:
    plugin:
        springsecurity:
            userLookup:
                userDomainClassName: library.User
                authorityJoinClassName: library.UserRole
                authority:
                    className: library.Role

            rest:
                login:
                    endpointUrl: /api/login
                    failureStatusCode: 401
                logout:
                    endpointUrl: /api/logout
                token:
                    generation:
                        jwt:
                            enabled: true
                            secret: 'x6lkl5qOS0wCwwXTP0UyYzJz74nixcKe'
                            expiration: 3600
                    storage:
                        jwt:
                            enabled: true
                            secret: 'x6lkl5qOS0wCwwXTP0UyYzJz74nixcKe'
                tokenValidation:
                    enableAnonymousAccess: true

            controllerAnnotations:
                staticRules:
                    - pattern: '/api/login'
                      access: [ 'permitAll' ]
                    - pattern: '/api/logout'
                      access: [ 'isAuthenticated()' ]
                    - pattern: '/api/secure/**'
                      access: [ 'ROLE_USER' ]
                    - pattern: '/api/public/**'
                      access: [ 'permitAll' ]
                    - pattern: '/index'
                      access: ['ROLE_STUDENT', 'ROLE_LIBRARIAN']
        quartz:
            autoStartup: true
            jdbcStore: false
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 5242880
            maxRequestSize: 5242880
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

dataSource:
    pooled: true
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    username: root
    password: Amer0598451852
    url: jdbc:mysql://localhost:3306/library?useSSL=false&serverTimezone=UTC

environments:
    development:
        dataSource:
            dbCreate: update
            pooled: true
            jmxExport: true
            driverClassName: com.mysql.cj.jdbc.Driver
            username: root
            password: Amer0598451852
            dialect: org.hibernate.dialect.MySQL8Dialect
            url: jdbc:mysql://localhost:3306/library?useSSL=false&allowPublicKeyRetrieval=true
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/library?useSSL=false&allowPublicKeyRetrieval=true
    production:
        dataSource:
            dbCreate: none
            url: jdbc:mysql://localhost:3306/library?useSSL=false&allowPublicKeyRetrieval=true
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

backup:
    directory: "C:/Users/Amer Eid/OneDrive/Desktop/backups"
    filenamePattern: "backup_${date}.sql"
    retentionDays: 14
    db:
        name: library
        username: root
        password: Amer0598451852
        host: localhost
        port: 3306
    mysqldumpPath: "C:/Program Files/MySQL/MySQL Server 8.0/bin/mysqldump.exe"
